### ISSUE TITLE
Add support for computational environments

### ISSUE THREAD

**Issue by PeerHerholz** [florianmahner/tomlparse#2]
Ahoi hoi @florianmahner,

thanks for creating this, it's really cool!

I was wondering if the tool could be extended to also support `computational environments`, ie an additional argument through which I can specify a `conda env` or `requirements.txt`/`.yml` through which the script should be run?
This could be really cool re reproducibility, etc. .

Thanks again. Cheers, Peer

**Comment by florianmahner** [comment]
hey! thanks for asking. we have made the project pip installable, which hopefully answers the question
