### ISSUE TITLE
tomllib.load is expecting a file descriptor (not path) with tomllib

### ISSUE THREAD

**Issue by jujumo** [florianmahner/tomlparse#8]
I am using python 3.11.0 and therefor `tomllib` packed with it.
In that situation, call to `tomllib.load` is expecting a file descriptor, 
and thus crash with the given file path.

`            config = tomllib.load(path)
`

I cant simply fix it, because `load` function API seems to differ between `tomllib` and `toml`:

 - tomllib: https://github.com/python/cpython/blob/9585a1a2a251aaa15baf6579e13dd3be0cb05f1f/Lib/tomllib/_parser.py#L57
 - toml: https://github.com/uiri/toml/blob/65bab7582ce14c55cdeec2244c65ea23039c9e6f/toml/decoder.py#L113

**Comment by florianmahner** [comment]
thanks for spotting this, will look into it asap

**Comment by jujumo** [comment]
From https://realpython.com/python311-tomllib/

Its seems its **tomli** that should be the fallback, not **toml**.

I revert the commit with the file descriptors, and it works for me. But I dont want to do PR, since I have no mean of proper testing.
